/**
 * 设计系统常量
 * 管理应用中使用的各种设计值
 */

export const DESIGN_CONSTANTS = {
  // 颜色值
  COLORS: {
    GRADIENT_START: '#f5f7fa',
    GRADIENT_END: '#c3cfe2',
    LOGIN_BG_WHITE: 'white',
    LOGIN_BORDER_COLOR: '#eee',
    SHADOW_COLOR_PRIMARY: 'rgba(50, 50, 93, 0.1)',
    SHADOW_COLOR_SECONDARY: 'rgba(0, 0, 0, 0.07)',
  },
  
  // 尺寸值
  SIZES: {
    LOGIN_FORM_MAX_WIDTH: '420px',
    LOGIN_BUTTON_HEIGHT: '45px',
    LOGIN_BORDER_RADIUS: '10px',
    LOGIN_PADDING: '40px',
    LOGIN_HEADER_MARGIN_BOTTOM: '30px',
    LOGIN_FOOTER_BORDER_WIDTH: '1px',
    LOGIN_SHADOW_BLUR_PRIMARY: '35px',
    LOGIN_SHADOW_BLUR_SECONDARY: '15px',
    LOGIN_SHADOW_OFFSET_X_PRIMARY: '0',
    LOGIN_SHADOW_OFFSET_X_SECONDARY: '0',
    LOGIN_SHADOW_OFFSET_Y_PRIMARY: '15px',
    LOGIN_SHADOW_OFFSET_Y_SECONDARY: '5px',
    LOGIN_LETTER_SPACING: '2px',
  },
  
  // 其他设计值
  VALUES: {
    LOGIN_GRADIENT_ANGLE: '135deg',
    LOGIN_FONT_WEIGHT: '500',
    LOGIN_SHADOW_OPACITY_PRIMARY: '0.1',
    LOGIN_SHADOW_OPACITY_SECONDARY: '0.07',
  }
}